const SET_ERROR = 'SET_ERROR'
const SET_ERROR_ALL = 'SET_ERROR_ALL'
const SET_ERROR_TEAM = 'SET_ERROR_TEAM'
const SET_IS_SUBMIT = 'SET_IS_SUBMIT'
const SET_TEAM_ID = 'SET_TEAM_ID'
const SET_KEY = 'SET_KEY'

export { SET_ERROR, SET_ERROR_TEAM, SET_IS_SUBMIT, SET_TEAM_ID, SET_KEY, SET_ERROR_ALL }
